# Generated by Django 3.2 on 2021-05-20 13:57

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed_by', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), size=None)),
                ('name', models.CharField(max_length=100)),
                ('duration', models.DurationField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(1, 'Одна Відповідь'), (2, 'Декілька відповідей'), (3, 'Написати Відповідь')], max_length=50)),
                ('test_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='core.testbase')),
            ],
        ),
        migrations.CreateModel(
            name='TestEstimationByType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(1, 'Одна Відповідь'), (2, 'Декілька відповідей'), (3, 'Написати Відповідь')], max_length=50)),
                ('size', models.PositiveIntegerField()),
                ('estimation', models.PositiveIntegerField()),
                ('test_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimation', to='core.testbase')),
            ],
        ),
        migrations.CreateModel(
            name='TaskSolving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_solving', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PracticalLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_at', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('pdf_file', models.FileField(upload_to='')),
                ('students', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), size=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practical_lesson', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_at', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('pdf_file', models.FileField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnswerOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('correct', models.BooleanField()),
                ('test_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='core.testitem')),
            ],
        ),
    ]
