# Generated by Django 3.2 on 2021-05-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='published_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='practicallesson',
            name='published_at',
            field=models.DateTimeField(),
        ),
    ]
